# You can add your name here
title: Victor Sanchez
# Use a relative path to logo image 
# TODO: update this image
logo: Profile.JPG
# Fix hyphenation 
description: With a decade in software development, I bring a wealth of expertise, driven by a relentless pursuit of excellence. Beyond code, I find inspiration in outdoor pursuits like trail running, mountain biking, and hiking, which invigorate my mind. Traveling fuels my curiosity, offering new cultural experiences and culinary delights.
# Fix spelling
show_downloads: false

# Theme 1
#theme: jekyll-theme-minimal 
#plugins:
#  - jekyll-seo-tag 

# Theme 2
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Allow visitors to contact you
email: vhsv90@gmail.com