# You can add your name here
title: Victor Sanchez
# Use a relative path to logo image 
# TODO: update this image
logo: Profile.JPG
# Fix hyphenation 
description: As a seasoned software developer with a decade of experience under my belt, I bring a wealth of knowledge and expertise to the table. My journey in software development has been marked by a relentless pursuit of excellence and a passion for pushing the boundaries of what's possible. Beyond the confines of code, I find solace and inspiration in the great outdoors. Trail running, mountain biking, hiking – these are not just hobbies but avenues for rejuvenation and exploration. The thrill of conquering new trails, the serenity of remote landscapes, and the camaraderie of outdoor adventures fuel my spirit and invigorate my mind. But my love for adventure doesn't end with physical pursuits. Traveling is my gateway to new cultures, cuisines, and experiences. Whether it's trekking through rugged mountains, sampling street food in bustling cities, or uncovering hidden gems off the beaten path, I thrive on the thrill of discovery and the joy of shared moments.
# Fix spelling
show_downloads: false

# Theme 1
theme: jekyll-theme-minimal 
plugins:
  - jekyll-seo-tag 

# Theme 2
#remote_theme: pages-themes/hacker@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one

# Allow visitors to contact you
email: vhsv90@gmail.com